### ISSUE TITLE
Wrong network configuration after install, when pass parameters with vlan

### ISSUE THREAD

**Issue by 6aKa** [yast/yast-network#1103]
Step for reproduce:

When install openSUSE Tumbleweed, config network with vlan on one interface with parameters "Boot options", example
ifcfg="eno1.55=192.168.10.10/24,192.168.10.1,1.1.1.1 8.8.4.4 8.8.8.8,mydomain.com"
After install run yast2, System -> Network Settings, than select eno1.55 interface and press edit.
Empty VLAN ID field, but expected 55.
And if change hostname and save - you got broken network.

**Comment by teclator** [comment]
We prefer bugzilla for reporting YaST bugs, and attaching yast logs is helpful / appreciated

https://en.opensuse.org/openSUSE:Report_a_YaST_bug

BTW, I already reproduced it and was testing a fix, so I will take care of creating the bug and the PR with the fix.

Thnx for the bug report.

**Comment by teclator** [comment]
Created https://bugzilla.opensuse.org/show_bug.cgi?id=1176575 and also a proposed fix https://github.com/yast/yast-network/pull/1104

**Comment by teclator** [comment]
Issue fixed by #1104 & #1105 , verified using a [dud](https://github.com/openSUSE/mkdud)
