### ISSUE TITLE
PR #1320 broke MicroOS Autoyast installation

### ISSUE THREAD

**Issue by hrak** [yast/yast-network#1322]
PR #1320 broke MicroOS Autoyast installation.

MicroOS AutoYast installation throws the following error:

<img width="529" alt="Screenshot 2023-01-24 at 14 48 29" src="https://user-images.githubusercontent.com/1963283/214314355-91ebf7b2-f042-4acf-a5ec-c616fe2b2c5c.png">

This is using `openSUSE-MicroOS-DVD-x86_64-Snapshot20230122-Media.iso`

I guess this should be something like this instead:

```ruby
dest_dir = include ? dest_path : ::File.dirname(::Pathname.new(dest_path))
```

**Comment by teclator** [comment]
Should be already fixed by https://github.com/yast/yast-network/pull/1320
