### ISSUE TITLE
bug in yast2-network

### ISSUE THREAD

**Issue by luckyboy94120** [yast/yast-network#1343]
Hi
at each Opensuse TW installation I have this error message. (in the
attached file). do you know what the problem is?
It's same when I try to connect after I install the distro, I fill all
the required fields and I think that's correct.
The fields I filled are on this post on the Alionet french forum - #post4

--https://www.alionet.org/index.php?PHPSESSID=97a0bdae4690eb5e97bc5d44a54e1111&topic=1577.msg13291#new

and there is my system-connection file is two posts later.
Do you have any idea of what the problem is?
Is it a wifi driver problem?
Thanks by advance,
J.

**Comment by dgdavid** [comment]
Hi there!

Not sure if the problem is solved or not. Anyway, for easing the investigation process it is better to 

* Attach the screenshot here (I'll do)
* Collect the logs and open a bug report as the installer proposed.

Regards.

**Comment by dgdavid** [comment]
> The fields I filled are on this post on the Alionet french forum - #post4

From the mentioned post, 

![yBkJC5m](https://github.com/yast/yast-network/assets/1691872/687acf8c-de3f-4609-98a9-e347875cc489)

**Comment by teclator** [comment]
As replied by email:

I already fixed it from SLE-15-SP3 (Leap 15.3) in advance, so the fix should be soon in Tumbleweed

- https://github.com/yast/yast-network/pull/1339 (SLE-15-SP3)
- https://github.com/yast/yast-network/pull/1342 (master / Tumbleweed)

- https://build.opensuse.org/request/show/1096794

So, consider it as fixed.
