### ISSUE TITLE
Missing Networkconfig in YaST2 for a Tunnel (SIT)

### ISSUE THREAD

**Issue by smithfarm** [yast/yast-network#551]
Günther J. Niederwimmer reports in https://bugzilla.opensuse.org/show_bug.cgi?id=754942

Hello,

I like to setup a 6in4 Tunnel, but with YaST2 it is not possible I don't found a entry for a "SIT" Tunnel.

Reproducible: Always

Log attached in https://bugzilla.opensuse.org/show_bug.cgi?id=754942#c3

**Comment by teclator** [comment]
There are some interfaces that are supported by wicked but not by YaST.

For the ifcfg-tunnel there was even a feature request:

https://fate.suse.com/320386

Recently we have done some refactorization in the module, and as part of the research we created a card with some of the supporter wicked configuration that is not supported by YaST yet:

ibchild on SLE11 and on sles12+ we've added macvlan (MACVLAN_DEVICE is set), macvtap (MACVTAP_DEVICE is set),team (TEAM_RUNNER set), ovs-bridge (OVS_BRIDGE=yes/no) and vxlan (VXLAN=yes/no)

- https://fate.suse.com/315131
- https://www.suse.com/documentation/sled-15/singlehtml/book_sle_admin/book_sle_admin.html#sec.network.manconf.files.ifcfg
- https://fate.suse.com/320386

Nanny policies.

That is, we will try to add support to them asap, thnx!
