### ISSUE TITLE
please release versions and use git tags

### ISSUE THREAD

**Issue by pavlix** [yast/yast-network#582]
Hi all, I am working with yast-network 3.3.6 in form of yast2-network package in Factory/Tumbleweed and I just wanted to use a git clone to make modifications and patches. But, suprisingly, there was no tag for 3.3.6 in the git repo and even more surprisingly, there was no version 3.3.6 even in the history, 3.3.8 was the closest that could be found in the files in the package directory.

It looks like the yast-network project doesn't have any versions or releases and that those are often created ad-hoc as part of the packaging process. That also sort of follows from the fact that there's no useage of the version number outside the package directory.

**Comment by jreidinger** [comment]
Hi @pavlix , we did not create tags in any yast repo as we use git repo itself and sending content to automatic to open build service.  When we need specific version, we simple find version in changes and checkout that version. But we usually not need specific version, but version in specific release like openSUSE Leap or SLE which have own branches like it is documented at http://yastgithubio.readthedocs.io/en/latest/maintenance-branches/#maintenance-branch-naming

**Comment by pavlix** [comment]
I see. I was just surprised that Tumbleweed uses a package with a release number (3.3.6) while the respective commit is nowhere to be found. My intention, as a beginner, was to make minimum changes against a version that already worked for me and work with it in Git to easily create patches just as I'm used to do as a package maintainer. I finally did it by gitizing the tarball from the source RPM instead.

**Comment by imobachgs** [comment]
Ok, so I guess we could close the issue as @pavlix has found a workaround that (hopefully) works for him.
