### ISSUE TITLE
Add GUI-controls for REMOTE_IPADDR= field

### ISSUE THREAD

**Issue by MikhailKasimov** [yast/yast-network#716]
Hello!

Initial report: [0] https://bugzilla.opensuse.org/show_bug.cgi?id=1120637

When network settings are put via ```yast2-network``` module, field ```REMOTE_IPADDR=``` is also got added, if one takes a look into generated ```/etc/sysconfig/network/ifcfg-{eth0, vlan, ...}``` config. But there is no GUI-controls in ```yast2-network``` to put remote address, if needed. Initially I thought (see [0]), it is vlan-settings issue, but no -- it is related to all network settings via ```yast2-network```. Please, consider. Thanks!

**Comment by teclator** [comment]
This can be considered a feature request and as there is no fate.opensuse.org anymore for requesting openSUSE features I have reopened the original bug and marked as an enhancement.

Will close this issue as we prefer to use bugzilla for this kind of requests.

Thnx!
